--
-- PostgreSQL database dump
--

\restrict kyuRmHMvJsMP7ehdYG1zmdN8cg8Iol4ysQBgplfXceeZc8CSgak4t1vc8UR2hAq

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: locations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.locations (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    location_type character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    parent_id bigint,
    CONSTRAINT locations_location_type_check CHECK (((location_type)::text = ANY ((ARRAY['PROVINCE'::character varying, 'DISTRICT'::character varying, 'SECTOR'::character varying, 'CELL'::character varying, 'VILLAGE'::character varying])::text[])))
);


ALTER TABLE public.locations OWNER TO postgres;

--
-- Name: locations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    role_name character varying(255) NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suppliers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.suppliers (
    id bigint NOT NULL,
    account_holder character varying(255) NOT NULL,
    account_no character varying(255) NOT NULL,
    address character varying(255) NOT NULL,
    bank_name character varying(255) NOT NULL,
    biz_cert character varying(255) NOT NULL,
    biz_type character varying(255) NOT NULL,
    capital double precision NOT NULL,
    country character varying(255) NOT NULL,
    currency character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    employees integer NOT NULL,
    fax character varying(255),
    password character varying(255) NOT NULL,
    po_box character varying(255),
    reg_date date NOT NULL,
    registered_at timestamp(6) without time zone NOT NULL,
    rep_email character varying(255) NOT NULL,
    rep_id character varying(255) NOT NULL,
    rep_name character varying(255) NOT NULL,
    rep_phone character varying(255) NOT NULL,
    rep_po_box character varying(255),
    rssb_no character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    supplier_name character varying(255) NOT NULL,
    tel1 character varying(255) NOT NULL,
    tel2 character varying(255),
    tin_no character varying(255) NOT NULL,
    website character varying(255)
);


ALTER TABLE public.suppliers OWNER TO postgres;

--
-- Name: suppliers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.suppliers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suppliers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_profiles (
    id bigint NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    phone_number character varying(255)
);


ALTER TABLE public.user_profiles OWNER TO postgres;

--
-- Name: user_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.user_roles OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    location_id bigint NOT NULL,
    profile_id bigint
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: locations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.locations (id, code, location_type, name, parent_id) FROM stdin;
1	PROV-01	PROVINCE	Kigali City	\N
2	DIST-01	DISTRICT	Gasabo	1
3	SECT-01	SECTOR	Remera	\N
4	CELL-01	CELL	Nyabisindu	\N
5	VILL-01	VILLAGE	Amarembo	\N
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, role_name) FROM stdin;
1	ADMIN
2	SUPPLIER
3	TENDER_MANAGER
\.


--
-- Data for Name: suppliers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.suppliers (id, account_holder, account_no, address, bank_name, biz_cert, biz_type, capital, country, currency, email, employees, fax, password, po_box, reg_date, registered_at, rep_email, rep_id, rep_name, rep_phone, rep_po_box, rssb_no, status, supplier_name, tel1, tel2, tin_no, website) FROM stdin;
1	Kigali Stationery Ltd	40010-9988776-55	KN 3 Ave, Kigali	Equity Bank	RDB_CERT_2024_03A.pdf	Stationery Supply	15000000	Rwanda	RWF	sales@kigalistationery.rw	15	\N	P@ssword321	P.O. Box 450 Kigali	2024-01-10	2026-03-13 12:56:56.176482	pumutoni@kigalistationery.rw	1199580000556677	Pauline Umutoni	+250789334455	P.O. Box 450 Kigali	RSSB-556677999	Pending Verification	Kigali Stationery Limited	+250788334455	\N	105655778	\N
2	Tech Solutions Rwanda LTD	00045-00123456-78	KN 3 Rd, Kigali City Center	Bank of Kigali	tech_solutions_cert2024.pdf	IT Hardware & Software	50000000	Rwanda	RWF	info@techsolutions.rw	25	+250252123456	SecurePassword123!	P.O. Box 732 Kigali	2020-05-15	2026-03-13 13:07:10.290797	jc.ndayisaba@techsolutions.rw	1198580002134098	Jean Claude Ndayisaba	+250788987654	P.O. Box 732 Kigali	RSSB-8839201	Pending Verification	Tech Solutions Rwanda LTD	+250788123456	+250738123456	100293847	www.techsolutions.rw
3	Global Builders Consortium	112233445566	Industrial Area, Enterprise Road, Nairobi	Equity Bank	global_builders_inc.pdf	Construction Materials	2500000	Kenya	USD	sales@globalbuilders.co.ke	150	\N	GlobalBuild2024!	P.O. Box 90120 Nairobi	2015-11-20	2026-03-13 13:07:36.175338	swanjiku@globalbuilders.co.ke	ID-KE-9012345	Sarah Wanjiku	+254722334455	\N	N/A	Pending Verification	Global Builders Consortium	+254700112233	\N	KRA99382711	www.globalbuilders.co.ke
4	Kigali Business Consultants	400123456789	KG 7 Ave, Heights Building, Kigali	I&M Bank	kbc_rdb_certificate.png	Consulting Services	5000000	Rwanda	RWF	contact@kbc.rw	5	\N	ConsultKigali#1	\N	2023-01-10	2026-03-13 13:07:56.278282	amutoni@kbc.rw	1199070003456012	Alice Mutoni	+250781112224	\N	RSSB-5566778	Pending Verification	Kigali Business Consultants	+250781112223	\N	103948576	\N
5	AgroVet East Africa LTD	200-9988776655-44	Musanze Town Market, Northern Province	BPR Atlas Mara	agrovet_license_2024.jpg	Agriculture & Veterinary Supply	120000000	Rwanda	RWF	supply@agrovet.rw	45	+250252334455	AgroPassword24!	P.O. Box 1122 Musanze	2018-08-05	2026-03-13 13:08:14.291137	e.habimana@agrovet.rw	1198080004567089	Emmanuel Habimana	+250783334477	P.O. Box 1122 Musanze	RSSB-1122334	Pending Verification	AgroVet East Africa LTD	+250783334455	+250783334456	100554433	\N
\.


--
-- Data for Name: user_profiles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_profiles (id, first_name, last_name, phone_number) FROM stdin;
1	HIRWA	Flora	0788111111
2	Jane	Supplier	0788222222
3	John	TenderManager	0788333333
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_roles (user_id, role_id) FROM stdin;
1	1
2	2
3	3
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, password, location_id, profile_id) FROM stdin;
1	kigali.admin@procurement.rw	AdminPassword123	5	1
2	contact@techsupplies.rw	SupplierPassword123	5	2
3	tenders@minict.gov.rw	TenderPassword123	5	3
\.


--
-- Name: locations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.locations_id_seq', 5, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 3, true);


--
-- Name: suppliers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.suppliers_id_seq', 5, true);


--
-- Name: user_profiles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_profiles_id_seq', 3, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 3, true);


--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: suppliers suppliers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: roles uk716hgxp60ym1lifrdgp67xt5k; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT uk716hgxp60ym1lifrdgp67xt5k UNIQUE (role_name);


--
-- Name: users uk7s5nlreekaxdbfml4ofky7utw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk7s5nlreekaxdbfml4ofky7utw UNIQUE (profile_id);


--
-- Name: suppliers ukj6t3dtmafntfaxh13j59qfq7h; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT ukj6t3dtmafntfaxh13j59qfq7h UNIQUE (tin_no);


--
-- Name: locations uknjcw38t3qcy312pglqpf3pd59; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT uknjcw38t3qcy312pglqpf3pd59 UNIQUE (code);


--
-- Name: suppliers ukq5uvp89ra4ksaty5ghyaw4kjr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT ukq5uvp89ra4ksaty5ghyaw4kjr UNIQUE (email);


--
-- Name: user_profiles user_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users fk9ni9y01cgm4kt2lp4d8smxm45; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk9ni9y01cgm4kt2lp4d8smxm45 FOREIGN KEY (profile_id) REFERENCES public.user_profiles(id);


--
-- Name: users fkdk0xfnnthbj8afp1ira6sndte; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkdk0xfnnthbj8afp1ira6sndte FOREIGN KEY (location_id) REFERENCES public.locations(id);


--
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: locations fkhjdkpuoptx1cd04r3atchkpi0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT fkhjdkpuoptx1cd04r3atchkpi0 FOREIGN KEY (parent_id) REFERENCES public.locations(id);


--
-- PostgreSQL database dump complete
--

\unrestrict kyuRmHMvJsMP7ehdYG1zmdN8cg8Iol4ysQBgplfXceeZc8CSgak4t1vc8UR2hAq

